apiVersion: opentofu.upbound.io/v1beta1
kind: Workspace
metadata:
  name: bucketanotherone
  annotations:
spec:
  forProvider:
    env:
      - name: TF_VAR_name
        value: bucketanotherone
      - name: TF_VAR_compartment_id
        value: <compartment_id>
      - name: TF_VAR_namespace
        value: <namespace>
      - name: TF_VAR_storage_tier
        value: Archive
    module: git::https://github.com/PZoli98/terraform-modules.git//bucket?ref=main
    source: Remote
  providerConfigRef:
    name: opentofu-providerconfig
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: bucketanotherone-connection